[package]
name = "nonproxy-subscription"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
url.workspace = true
webpki-roots.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
