[package]
name = "nonproxy-windows-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
socket2.workspace = true
tokio.workspace = true
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_Dns",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
] }

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
