<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NonProxy</RootNamespace>
    <AssemblyName>NonProxy.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../../../generated/csharp/**/*.cs"
             LinkBase="Generated" />
  </ItemGroup>

</Project>
