[package]
name = "nonproxy-windows-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
nonproxy-model = { path = "../nonproxy-model" }
sha2.workspace = true
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_WindowsFilteringPlatform",
  "Win32_Security",
  "Win32_Security_Cryptography",
  "Win32_Security_Cryptography_Catalog",
  "Win32_Security_Cryptography_Sip",
  "Win32_Security_WinTrust",
  "Win32_Security_Isolation",
  "Win32_Storage_Packaging_Appx",
  "Win32_System_Threading",
] }

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
